# Generated by Django 2.2.7 on 2020-02-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=45)),
                ('sobrenome_autor', models.CharField(max_length=45)),
                ('datanasc_autor', models.DateField()),
                ('sexo_autor', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
            ],
            options={
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=45)),
                ('cod_categoria', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_editora', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'editora',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_livro', models.CharField(max_length=45)),
                ('subtitulo_livro', models.CharField(blank=True, max_length=45, null=True)),
                ('avaliacao_livro', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('isbn_livro', models.CharField(max_length=13)),
                ('publicacao_livro', models.DecimalField(decimal_places=0, max_digits=4)),
                ('categoria_cod_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioLivros.Categoria')),
                ('editora_cod_editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioLivros.Editora')),
            ],
            options={
                'db_table': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='AutorLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_autorlivro', models.IntegerField()),
                ('autor_funcao', models.CharField(max_length=20)),
                ('autor_cod_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioLivros.Autores')),
                ('livro_cod_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioLivros.Livros')),
            ],
            options={
                'db_table': 'autorlivro',
            },
        ),
    ]
