# Generated by Django 2.2.7 on 2020-01-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioLivros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=100)),
                ('sexo_autor', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='AutorLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_autorlivro', models.IntegerField()),
                ('autor_funcao', models.CharField(max_length=20)),
                ('autor_cod_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioLivros.Autores')),
                ('livro_cod_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioLivros.Livros')),
            ],
            options={
                'db_table': 'autorlivro',
            },
        ),
    ]
