# Generated by Django 2.2.7 on 2019-11-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioLivros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='isbn_livro',
            field=models.IntegerField(),
        ),
    ]
