# Generated by Django 2.2.7 on 2020-01-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioLivros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='capa_livro',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='sinopse_livro',
        ),
        migrations.AlterField(
            model_name='livros',
            name='avaliacao_livro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
    ]
