# Generated by Django 2.2.7 on 2019-11-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioLivros', '0002_auto_20191126_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cod_categoria',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
