# Generated by Django 2.2.7 on 2020-01-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioLivros', '0002_autores_autorlivro'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='datanasc_autor',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autores',
            name='sobrenome_autor',
            field=models.CharField(default='sobrenome', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autores',
            name='nome_autor',
            field=models.CharField(max_length=45),
        ),
    ]
