# Generated by Django 2.2.7 on 2020-01-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioLivros', '0002_auto_20200110_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='avaliacao_livro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
