# Generated by Django 2.2.7 on 2019-11-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioLivros', '0003_categoria_cod_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='capa_livro',
        ),
    ]
