# Generated by Django 2.2.7 on 2019-11-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioLivros', '0004_remove_livros_capa_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='isbn_livro',
            field=models.CharField(max_length=13),
        ),
    ]
